language: node_js
node_js:
- 10
services:
- docker
jobs:
  include:
  - stage: test
    install: npm install
    script:
    - npm test
  - stage: build and publish docker image
    script:
    - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t $DOCKER_USERNAME/deploy-expressapp-to-k8s:$TRAVIS_BUILD_NUMBER
      --build-arg SHA=$(git rev-parse --short HEAD) .
    deploy:
      skip_cleanup: true
    - provider: script
      script: "./bin/docker_push.sh"
      on:
        branch: master
    - provider: script
      script: "./bin/docker_push.sh"
      on:
        tags: true
env:
  global:
    secure: 1QwA5mLxK1ff4fTaJXTCJpPfQCNS2Mu+AVE3s+iOX9Q4YTzQb8fX6XUIXwFzROweWjSMxffgGUEgQM3/pYhn8yXE5M9QlzBN647NSa1dNOhKhzwRFigMsE2qCPaeSHyzzzSm8eZM+MtOoZ/0GXTAR+exUOlz/VoO4kHIyOuM9V9VPzgjBnGyZlZS+i3eoSA2FmbywUB5dOE68zkUDF+D/1whZITcT8yDpmiMq1X9Y4UT22AJjRFz5NWEShlGwFozCf3YDU9YQRCrCWfmcAze1Z6foSkljxixD8d0+bsxmQUWcWH26a/SSU5bPt/UBr4N3dv5rXXHo6tjEo2AAb4dvChqN6DW6P9SCO4rL9CCLz+ioeYPkzfEU0lGB0pxHNozCzZADWVnoDJPEpv/uaVu4yAbBs7HevMN7t5Y+jCrHuP9abMiciGCSUW4B2kRZ95+Z8RlumTbz8gP60Vz0r+4fTpj9kZmDNVcmQkD9G17bk8NuM/NSxVuAdg2Y4+Ku78qSEmzKGtsUKafPb3FEsXslp0g7nEWTn8w67ZdT6LMQB+Bo0xXNSgOcziTg9TaVOjS9/zdem0i/rP7RiA3Z3nW4aaF5M5oq86l/O+mNFzzsJMvCCtsZ4T3zSwRriLK6vQnyqeW2gAwu6QICw8E8t+ZuCIZlvoXFyw4g0uNfaLm/2c=
