language: node_js
node_js:
- 10
services:
- docker
jobs:
  include:
  - stage: test
    install: npm install
    script:
    - npm test
  - stage: build and publish docker image
    script:
    - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t $DOCKER_USERNAME/deploy-expressapp-to-k8s:$TRAVIS_BUILD_NUMBER
      --build-arg SHA=$(git rev-parse --short HEAD) .
    deploy:
    - provider: script
      script: "./bin/docker_push.sh"
      on:
        branch: master
    - provider: script
      script: "./bin/docker_push.sh"
      on:
        tags: true
env:
  global:
    secure: lFevsKZJnovndM94Ej/RAD1azb8oJ6rEXWH4gXeJ/PEAbrXsYNv3PtTxciQgXIs0pBVGMr3RquHzPlkKK5n4l0Se0nu3CDv6NFRAhy2ZUfWsKy9hw1RwmNdXhS496chpAh+i7KFzIoemd8Q6mtdum4/+O7PBTVtvWXJNDNbn/H+A6+v3cc7Aj/rdOqqD5Qnt/ul6B1zdJkPjMbnV/3DzmZdduZP/KerTPXQAofrNy6NdzVbSBBiN5CFolrf1u1kWyBZDGk1EDyx/8qpVI0Z7RRgmmh/htmRxQECKJjS9aYEi6zmZTjuB4A3pVGnzHjanLLgYkfGdF/RlgvhXZaKvnEO2S6xDux0xB/Ajet9Wyg9T47uwWIh12dFvwquJ6K4puUtRdCKAPNYim+wD0dCJQ8XZv/Z15M8ZQorLCiFuC6BUgD0gtILfuORiRQQqSVYqBDDxLPpjMHTD6zgyhKI+Ch+j1VZsjj6F4yWM1pQ3MbdAlkTbFGoWADmtBiiKq2eclBlDwkaciUiXpR1mJ5U/Jm07XQC4H1MQewxpA73WUowyVbQpV/U/vpO1EQx5j0yOcIWovqNERm5GA5tvfpzf23pCyf/Tnxgp0SUTIJ2KWyKNGOY15cXk2bB2ajWdkQz5KA0RDt///H8pRQvzh0qhdV5nn0YJ5PzgIAYnMWuI14k=
