apiVersion: v1
kind: Service
metadata:
  name: nodeapi-service
  namespace: technical-test
  labels:
    app: nodeapi
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: nodeapi